sudo: required
dist: xenial

matrix:
  include:
  - language: java

    jdk:
      - openjdk10

    services:
      - postgresql

    addons:
      postgresql: "9.5"

    before_script:
      - psql -c 'create database users_regsitration_test;' -U postgres

    before_install:
      - sudo /etc/init.d/postgresql stop
      - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
      - sudo apt-get update
      - sudo apt-get install postgresql-9.5


    env:
      global:
        - PGUSER=postgres
        - PGPORT=5432
        - PGHOST=localhost

    script:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test

    after_script:
      - bash <(curl -s https://codecov.io/bash) -cF java


  - language: node_js
    node_js:
      - 10
    cache:
      directories:
        - node_modules

    before_install:
      - cd web-app
      - yarn install


    script:
      - yarn run test:unit

    after_script:
      - bash <(curl -s https://codecov.io/bash) -cF javascript

